'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace UserControls


    Partial Public Class AddCommentForm

        ''' <summary>
        ''' AddCommentFormLayout control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AddCommentFormLayout As Global.DevExpress.Web.ASPxFormLayout

        ''' <summary>
        ''' Name control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Name As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' Email control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Email As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' Notes control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Notes As Global.DevExpress.Web.ASPxMemo

        ''' <summary>
        ''' Submit control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Submit As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace