'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System

Namespace UserControls
    Partial Public Class BlogNavigation

        ''' <summary>
        ''' BlogCategoriesNavBar control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected BlogCategoriesNavBar As Global.DevExpress.Web.ASPxNavBar
    End Class
End Namespace